#!/bin/bash
# This file should not be modified -- make local changes to
# /etc/ppp/ip-down.local instead

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

LOGDEVICE=$6
REALDEVICE=$1

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

cp -f /etc/resolv.conf /etc/resolv.conf.tmp
fgrep -v "# ppp temp entry" /etc/resolv.conf.tmp > /etc/resolv.conf
chmod 0644 /etc/resolv.conf
rm -f /etc/resolv.conf.tmp

/etc/ppp/ip-down.ipv6to4 ${LOGDEVICE}

[ -x /etc/ppp/ip-down.local ] && /etc/ppp/ip-down.local "$@"

# These variables are for the use of the scripts run by run-parts
PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"
export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM

if [ -d /etc/ppp/ip-down.d/ -a -x /usr/bin/run-parts ]; then   
    /usr/bin/run-parts /etc/ppp/ip-down.d/
fi

/etc/sysconfig/network-scripts/ifdown-post --realdevice ${REALDEVICE} \
    ifcfg-${LOGDEVICE}

exit 0
