.TH DOEXEC 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH NOME
doexec \- lancia un eseguibile con un argv[0] arbitrario
.SH SINTASSI
.B doexec
\fI/path/dell/eseguibile\fP \fIargv[0]\fP [\fIargv[1-n]\fP]
.SH DESCRIZIONE
.B doexec
semplicemente lancia l'eseguibile con la lista degli argv fornita.
Ti permette di specificare un argv[0] diverso dal nome dell'eseguibile.
.SH OPZIONI
Tutte le opzioni vengono passate nella lista degli argv all'eseguibile
che viene lanciato.
