#!/bin/bash
# Description: Launch diverses Mandriva Scripts on boot.
# (c) Mandriva, Chmouel Boudjnah <chmouel@mandriva.com>
# 	$Id$

# Source functions
. /etc/rc.d/init.d/functions

[ -e /etc/sysconfig/system ] && . /etc/sysconfig/system

# /etc/issue and /etc/issue.net stuff

[ -f /etc/sysconfig/system ] && source /etc/sysconfig/system
[ -f /etc/sysconfig/msec ] && source /etc/sysconfig/msec
[ -z "$SECURE_LEVEL" ] && SECURE_LEVEL=3
[ -f /etc/sysconfig/init ] && source /etc/sysconfig/init
if [ $SECURE_LEVEL -lt 4 ]; then
    [ -z "$REWRITEISSUE" ] && REWRITEISSUE=rewrite
    if [ $SECURE_LEVEL -lt 3 ]; then
	[ -z "$REWRITEISSUENET" ] && REWRITEISSUENET=rewrite
    fi
fi

SYSTEM=${SYSTEM="OpenMandriva Lx"}
R=$(cat /etc/release)

if [ -r /etc/sysconfig/oem ]; then
    . /etc/sysconfig/oem

    if [ -n "$SYSTEM" -a -n "$PRODUCT" ]; then
	R="$SYSTEM $PRODUCT for `uname -m`"
    fi
fi


if [ "$REWRITEISSUE" = "rewrite" -a -f /etc/release ]; then

    arch=$(uname -m)
    a="a"
    case "_$arch" in
	    _a*) a="an";;
	    _i*) a="an";;
    esac

    NUMPROC=`egrep -c "^cpu[0-9]+" /proc/stat`
    if [ "$NUMPROC" -gt "1" ]; then
        SMP="$NUMPROC-processor "
	[ "$NUMPROC" = "2" ] && \
	SMP="Dual-processor "
        if [ "$NUMPROC" = "8" -o "$NUMPROC" = "11" ]; then
            a="an"
	else
	    a="a"
        fi
    fi

    # This will overwrite /etc/issue at every boot.  So, make any changes you
    # want to make to /etc/issue here or you will lose them when you reboot.

    if [ -x /usr/bin/linux_logo ]; then
	/usr/bin/linux_logo -t "$R" -f | sed -e 's|\\|\\\\|g' > /etc/issue
    else
	echo "$R" > /etc/issue
	echo "Kernel $(uname -r) on $a $SMP$(uname -m) / \l" >> /etc/issue
    fi

    if [ "$REWRITEISSUENET" = "rewrite" ]; then
	echo "Welcome to ${HOST}" > /etc/issue.net
	echo "$R" >> /etc/issue.net
	echo "Kernel $(uname -r) on $a $SMP$(uname -m)" >> /etc/issue.net
    else
	NAME="$SYSTEM"
	gprintf "Welcome to %s\n" "$NAME" > /etc/issue.net
	echo "-------------------------" >> /etc/issue.net
    fi
else
    if [ -f /etc/security/msec/issue.$SECURE_LEVEL ]; then
	cat /etc/security/msec/issue.$SECURE_LEVEL > /etc/issue
    elif [ -f /etc/security/msec/issue ]; then
	cat /etc/security/msec/issue > /etc/issue
    else
	rm -f /etc/issue
    fi
    if [ -f /etc/security/msec/issue.net.$SECURE_LEVEL ]; then
	cat /etc/security/msec/issue.net.$SECURE_LEVEL > /etc/issue.net
    elif [ -f /etc/security/msec/issue.net ]; then
	cat /etc/security/msec/issue.net > /etc/issue.net
    else
	rm -f /etc/issue.net
    fi
fi
