#!/bin/sh

uname_r=$(uname -r)

# Adjust symlinks as necessary in /boot to keep system services from
# spewing messages about mismatched System maps and so on.
if [ -L /boot/System.map -a -r /boot/System.map-$uname_r -a \
        ! /boot/System.map -ef /boot/System.map-$uname_r ] ; then
        ln -s -f System.map-$uname_r /boot/System.map
fi
if [ ! -e /boot/System.map -a -r /boot/System.map-$uname_r ] ; then
        ln -s -f System.map-$uname_r /boot/System.map
fi

# Adjust symlinks as necessary in /boot to have the default config
if [ -L /boot/config -a -r /boot/config-$uname_r ] ; then
        ln -sf config-$uname_r /boot/config
fi
if [ ! -e /boot/config -a -r /boot/config-$uname_r ] ; then
        ln -sf config-$uname_r /boot/config
fi
