.TH CONSOLETYPE 1 "Red Hat, Inc" "RH" \" -*- nroff -*-
.SH НАЗВАНИЕ
.B consoletype
\- отображает тип консоли, подключенной к стандартному вводу
.SH СИНТАКСИС
.B consoletype
.SH ОПИСАНИЕ
.B consoletype
отображает тип консоли, подключенной к стандартному вводу. Он выводит
.I vt
если консоль является виртуальным терминалом (устройство /dev/tty* или /dev/console, если не на последовательной консоли),
.I serial
если стандартным вводом является последовательная консоль (/dev/console или /dev/ttyS*) и
.I pty
если стандартный ввод является псевдотерминалом.
.SH ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ
.B consoletype возвращает
.TP
.I 0
если на виртуальном терминале
.TP
.I 1
если на последовательной консоли
.TP
.I 2
если на псевдотерминале.
.SH ПЕРЕВОД
Павел Марьянов acid_jack@ukr.net

