.TH DETECTLOADER 8 "Апрель 2000" "initscripts" "MandrakeSoft"
.SH НАЗВАНИЕ
detectloader \- определяет, какой тип загрузчика имеется на вашем диске.
.SH ОПИСАНИЕ
.PP
\fBdetectloader\fR определяет тип начального загрузчика, имеющийся на вашем \fBMBR\fR. Он находит первый диск посредством /proc/partitions и смотрит по магической последовательности, какой тип начального загрузчика у вас установлен.
.SH ОГРАНИЧЕНИЕ
.PP
Поддерживаются только grub, lilo и yaboot (начальные загрузчики, используюемые в \fBLinux Mandrake\fR). Приветствуются патчи для других начальных загрузчиков.
.SH COPYRIGHT
Copyright \(co 1999/2000 MandrakeSoft.
.PP
Это открытое программное обеспечение; условия копирования смотрите в исходных текстах. Ничего НЕ гарантируется; даже РАБОТОСПОСОБНОСТЬ или ПРИГОДНОСТЬ ДЛЯ ЛИЧНЫХ ЦЕЛЕЙ.
.SH ПЕРЕВОД
Павел Марьянов <acid_jack@ukr.net>
