.TH DOEXEC 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH НАЗВАНИЕ
doexec \- запускает исполняемый файл с произвольным argv[0]
.SH СИНТАКСИС
.B doexec
\fI/путь/к/исполняемому/файлу\fP \fIargv[0]\fP [\fIargv[1-n]\fP]
.SH ОПИСАНИЕ
.B doexec
просто запускает исполняемый файл со списком аргументов. Он позволяет вам задавать argv[0], кроме имени исполняемого файла.
.SH ОПЦИИ
Все опции заносятся в список argv для исполняемого файла.
.SH ПЕРЕВОД
Павел Марьянов acid_jack@ukr.net

