.TH NETREPORT 1 "Red Hat, Inc." "RH" \" -*- nroff -*-
.SH НАЗВАНИЕ
netreport \- запрашивает извещение об изменении сетевого интерфейса
.SH СИНТАКСИС
.B netreport
\fI[\fP-r\fI]\fP
.SH ОПИСАНИЕ
.B netreport
приказывает скриптам управления сетью послать сигнал SIGIO
процессу netreport, когда происходит изменение статуса какого-
либо сетевого интерфейса.
.SH ОПЦИИ
.TP
.B -r
Удаляет текущий запрос (если есть) для вызова процесса.
.PP
.SH ПРИМЕЧАНИЯ
Если программа не вызывает netreport с опцией
.B -r
до его существования, и другой процесс с таким же PID, созданный
до того, как имеют место изменения статуса интерфейса, тогда
возможно, что новый процесс получит фиктивный SIGIO.
.SH ПЕРЕВОД
Павел Марьянов <acid_jack@ukr.net>

