.TH PPP-WATCH 8 "Red Hat, Inc." "RHS" \" -*- nroff -*-
.SH НАЗВАНИЕ
ppp-watch \- демон, делающий работу интерфейсов PPP более похожей на
другие интерфейсы
.SH СИНТАКСИС
.B ppp-watch
\fIимя_интерфейса\fP \fIимя_интерфейса\fP [boot]
.SH ОПИСАНИЕ
.B ppp-watch
управляет одним соединением РРР, включая установку, разрыв и повторный
набор номера. Он выполняет синхронные действия по установке и разрыву
соединения.

.B ppp-watch
не предназначен для непосредственного запуска. Он должен использоваться
только из скрипта ifup-ppp.
.SH ОПЦИИ
.TP
.I имя_интерфейса
Имя поднимаемого интерфейса РРР.
.TP
boot
ppp-watch вызвается во время загрузки и должен будет завершить свою
работу через некоторое время, если соединение РРР не завершит установку,
чтобы не подвесить последовательность начальной загрузки.
.SH ПЕРЕВОД
Павел Марьянов <acid_jack@ukr.net>

