.TH USERNETCTL 8 "Red Hat, Inc." "RHS" \" -*- nroff -*-
.SH НАЗВАНИЕ
usernetctl \- позволяет пользователю вручную управлять сетевым
интерфейсом, если у него хватает прав
.SH СИНТАКСИС
.B usernetctl
\fIимя_интерфейса\fP up\fI|\fPdown\fI|\fPreport
.SH ОПИСАНИЕ
.B usernetctl
проверяет, разрешено ли пользователям вручную управлять сетевым
интерфейсом, заданным как \fIимя_интерфейса\fP, а затем пытается поднять
или опустить сетевой интерфейс, если в командной строке были заданы "up"
или "down", или возвращает статус "истина" или "ложь" (соответственно),
если была задана опция "report".

.B usernetctl
не предназначен для непосредственного запуска пользователями, тем не
менее он прекрасно работает и таким способом. Он используется в качестве
оболочки для скриптов ifup и ifdown, поэтому пользователи могут выполнять
те же действия в качестве root'а:
.nf
ifup \fIinterface-name\fP
ifdown \fIinterface-name\fP
.fi
и \fBifup\fP, и \fBifdown\fP автоматически вызовут usernetctl, чтобы
позволить изменить статус интерфейса.
.SH ОПЦИИ
.TP
.I "\fIимя_интерфейса"
Имя проверяемого сетевого интерфейса, например, ?ррр0?. Для обеспечения
совместимости с более ранними версиями поддерживаются также интерфейсы
"ifcfg-ppp0" и "/etc/sysconfig/network-scripts/ifcfg-ppp0".
.TP
up\fI|\fPdown
Пытается поднять или опустить интерфейс.
.TP
report
Сообщает, могут ли пользователи поднимать или опускать интерфейс.

.SH ФАЙЛЫ
.IR /etc/sysconfig/network-scripts/ifcfg-*

.SH ПРИМЕЧАНИЯ
Смена настроек устройства может унаследовать разрешения конфигурации по
умолчанию.

.SH ПЕРЕВОД
Павел Марьянов <acid_jack@ukr.net>

