.TH USLEEP 1 "Red Hat, Inc" \" -*- nroff -*-
.SH НАЗВАНИЕ
usleep \- засыпает на некоторое число микросекунд
.SH СИНТАКСИС
.B usleep
[\fIчисло\fP]
.SH ОПИСАНИЕ
.B usleep
засыпает на несколько микросекунд. По умолчанию на 1.
.SH ОПЦИИ
\fI--usage\fP
Показывает короткое сообщение об использовании.
.TP
\fI--help, -?\fP
Выводит справочную информацию.
.TP
\fI-v, --version\fP
Выводи информацию о версии.
.SH ОШИБКИ
Вероятно неточен на многих машинах вплоть до микросекунды. Расчет
производится с точностью только до -4 или, возможно, до -5.
.SH АВТОР
Donald Barnes <djb@redhat.com>
.br
Erik Troan <ewt@redhat.com>
.SH ПЕРЕВОД
Павел Марьянов <acid_jack@ukr.net>

