.TH DOEXEC 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH NÁZEV
doexec \- spustí spustitelný soubor s libovolným parametrem argv[0]
.SH SYNAPSE
.B doexec
\fI/path/to/executable\fP \fIargv[0]\fP [\fIargv[1-n]\fP]
.SH POPIS
.B doexec
jednoduše spustí spustitelný soubor se zadaným seznamem parametrů argv.  Umožní zadat
parametr argv[0] jiný než název spustitelného souboru.
.SH VOLBY
Všechny volby jsou předány v seznamu parametrů argv spustitelnému souboru, který spouštíte.
