.TH USLEEP 1 "Red Hat, Inc" \" -*- nroff -*-
.SH NÁZEV
usleep \- spí zadaný počet mikrosekund
.SH SYNAPSE
.B usleep
[\fIčíslo\fP]
.SH POPIS
.B usleep
spí zadaný počet mikrosekund. Výchozí počet mikrosekund je 1.
.SH VOLBY
\fI--usage\fP
Zobrazí krátkou zprávu s návodem pro použití.
.TP
\fI--help, -?\fP
Zobrazí informace s nápovědou.
.TP
\fI-v, --version\fP
Zobrazí informace o verzi.
.SH CHYBY
Na mnohých počítačích nebude program pravděpodobně přesný na mikrosekundu. 
Počítejte pouze s přesností plus mínus 4 nebo 5 mikrosekund.
.SH AUTOR
Donald Barnes <djb@redhat.com>
.br
Erik Troan <ewt@redhat.com>
