.TH "DETECTLOADER" "8" "Apr. 2000" "initscripts" "MandrakeSoft"
.SH "NIMI"
detectloader \- Tuvastab, millist tüüpi laadija Teie kõvakettal asub.
.SH "KIRJELDUS"
.PP 
\fBdetectloader\fR tuvastab alglaaduri, mis asub Teie arvuti \fBMBR\fR\-il. Esimene ketas leitakse /proc/partitions abil ning niinimetatud maagilise seerianumbri järgi tuvastatakse, milline alglaadur on Teie masinale paigaldatud.
.SH "PIIRANG"
.PP 
Toetatud on ainult grub, lilo, and yaboot (alglaadurid, mida me kasutame \fBMandrake Linuxi\fR tarbeks). Kuid teretulnud on lisandused ka teiste alglaadurite jaoks.
.SH "AUTORIÕIGUS"
Copyright \(co 1999/2000 MandrakeSoft.
.PP 
See on vaba tarkvara; kopeerimistingimusi vaadake lähtetekstist. Sellega ei kaasne MINGIT garantiid, isegi mitte KESKMISE/TAVALISE KVALITEEDI või TEATUD EESMÄRGIKS SOBIVUSE garantiid.
.SH "AUTOR"
Tõlge eesti keelde 2002: Marek Laane
.br 
bald@online.ee
