.TH "DOEXEC" "1" "Red Hat Software" "RHS" "\""
.SH "NIMI"
doexec \- käivitab käivitusfaili suvandiga argv[0]
.SH "KOKKUVÕTE"
.B doexec
\fI/käivitusfaili/asukoht\fP \fIargv[0]\fP [\fIargv[1\-n]\fP]
.SH "KIRJELDUS"
.B doexec
lihtsalt käivitab käivutusfaili toodud argv\-loendiga. See lubab Teil määrata argv[0] muuks kui käivitusfaili nimeks.
.SH "VÕTMED"
Kõik argv\-loendis kasutatavad võtmed saadetakse käivitatavale käivitusfailile.
