.TH "USLEEP" "1" "Red Hat, Inc" "\"" "-*-"
.SH "NIMI"
usleep \- magab teatud hulga mikrosekundeid
.SH "KOKKUVÕTE"
.B usleep
[\fInumber\fP]
.SH "KIRJELDUS"
.B usleep
paneb määratud mikrosekunditeks magama. Vaikeväärtus on 1.
.SH "VÕTMED"
\fI\-\-usage\fP
Näitab lühikest kasutusjuhist.
.TP 
\fI\-\-help, \-?\fP
Näitab abiinfot.
.TP 
\fI\-v, \-\-version\fP
Näitab versiooniinfot.
.SH "VEAD"
Paljudel masinatel ei pruugi toimida mikrosekundilise täpsusega. Kindlalt tasub arvestada täpsusega vaid \-4 või isegi \-5 mikrosekundit.
.SH "AUTOR"
Donald Barnes <djb@redhat.com>
.br 
Erik Troan <ewt@redhat.com>
.br 

.br 
Tõlge eesti keelde 2002: Marek Laane
.br 
bald@online.ee
