.TH DOEXEC 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH NOME
doexec \- executar um executável com um argv[0] arbitrário
.SH SINOPSIAS
.B doexec
\fI/caminho/para/executável\fP \fIargv[0]\fP [\fIargv[1-n]\fP]
.SH DESCRIÇÃO
.B doexec
simplesmente executa o executável com a lista argv fornecida.  Ela permite você 
especificar um outro argv[0] que o nome do executável.
.SH OPÇÕES
Todoas as opções são passadas na lista do argv para o executável ser executado.
