.TH CONSOLETYPE 1 "Red Hat, Inc" "RH" \" -*- nroff -*-
.SH НАЗВА
.B consoletype
\- виводить на друк тип консолі, яка підключена на стандартного вводу
.SH ВИКОРИСТАННЯ
.B consoletype
.SH ОПИС
.B consoletype
виводить на друк тип консолі, яка підключена на стандартного вводу. Друкує
.I vt
, якщо консоль \- це віртуальний термінал (/dev/tty* або /dev/console
пристрій, якщо не знаходиться на послідовній консолі),
.I serial
якщо стандартна консоль \- послідовний канал  (/dev/console чи /dev/ttyS*) і
.I pty
якщо стандартний ввід \- псевдо термінал.
.SH КОД ПОМИЛКИ
.B consoletype
повертає
.TP
.I 0
якщо знаходиться на віртуальному терміналі
.TP
.I 1
на послідовній консолі
.TP
.I 2
на псевдо терміналі
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
