.TH DETECTLOADER 8 "Apr 2000" "initscripts" "MandrakeSoft"
.SH НАЗВА
detectloader \- Визначає який тип менеджера завантаження встановлено
на диску.
.SH ОПИС
.PP
\fBdetectloader\fR визначає тип менеджера завантаження, який
встановлено в \fBMBR\fR. Він знаходить перший диск користуючись
/proc/partitions і за допомогою магічного номера визначає який
менеджер завантаження встановлено.
.SH ІСНУЮЧІ ОБМЕЖЕННЯ
.PP
Підтримує тільки grub, lilo, та  yaboot (менеджери завантаження, якими
ми користуємось для  \fBLinux
Mandrake\fR). Латки для додання підтримки інших менеджерів приймаються.
.SH COPYRIGHT
Copyright \(co 1999/2000 MandrakeSoft.
.PP
Це \- вільне програмне забезпечення; див. вихідні тексти програми для
знаходження інформації про умови дублювання.  Не надається ЖОДНОЇ
ГАРАНТІЇ; навіть щодо МОЖЛИВОСТЕЙ ПРОДАЖУ чи щодо ВІДПОВІДНОСТІ ДЛЯ
ПЕВНОГО ВИКОРИСТАННЯ.
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
