.TH DOEXEC 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH НАЗВА
doexec \- виконує програму з будь-якими вказаними параметрами argv[0]
.SH ВИКОРИСТАННЯ
.B doexec
\fI/path/to/executable\fP \fIargv[0]\fP [\fIargv[1-n]\fP]
.SH ОПИС
.B doexec
просто виконує програми з наданим списком командних аргументів.
Команда дозволяє вказати argv[0], який відрізняється від назви файлу програми.
.SH ПАРАМЕТРИ
Всі параметри передаються в списку argv програмі, яка виконується.
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
