.TH NETREPORT 1 "Red Hat, Inc." "RH" \" -*- nroff -*-
.SH НАЗВА
netreport \- вимагає надсилання повідомлень про зміни в мережевих інтерфейсах
.SH ВИКОРИСТАННЯ
.B netreport
\fI[\fP-r\fI]\fP
.SH ОПИС
.B netreport
повідомляє скриптам керування мережею, що вони повинні надсилати
сигнал SIGIO процесу, який викликає netreport при будь-якій зміні
мережевого інтерфейсу.
.SH ПАРАМЕТРИ
.TP
.B -r
Забрати запит (якщо такий є) для викликаючого процесу.
.PP
.SH ПРИМІТКИ
Якщо програма не викликала netreport з параметром
.B -r
перш, ніж закінчити свою роботу і після цього утворився процес з таким
самим PID перш, ніж змогли відбутися будь-які зміни в інтерфейсах,
існує можливість надсилання помилкового сигналу SIGIO новонародженому
процесу. 
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
