.TH PPP-WATCH 8 "Red Hat, Inc." "RHS" \" -*- nroff -*-
.SH НАЗВА
ppp-watch \- демон, який дозволяє представляти інтерфейс PPP більш
подібним до інших інтерфейсів
.SH ВИКОРИСТАННЯ
.B ppp-watch
\fIназва-інтерфейсу\fP \fIназва-інтерфейсу\fP [boot]
.SH ОПИС
.B ppp-watch
керує одним з'єднанням через PPP, включаючи старт, зупинку та
повторний дозвін. Робить так, що старт та зупинка стають синхронними.

.B ppp-watch
не повинен викликатися безпосередньо користувачем.  Має
використовуватись тільки з скрипту ifup-ppp.
.SH ПАРАМЕТРИ
.TP
.I назва-інтерфейсу
Назва інтерфейсу для старту (підйому).
.TP
boot
ppp-watch викликається під час завантаження і повинен закінчитись
через певний час затримки якщо з'єднання PPP не активізувалось
коректно для того, щоб не підвісити послідовність завантаження.
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
