.TH USLEEP 1 "Red Hat, Inc" \" -*- nroff -*-
.SH НАЗВА
usleep \- заснути на вказану кількість мікросекунд
.SH ВИКОРИСТАННЯ
.B usleep
[\fIчисло\fP]
.SH ОПИС
.B usleep
спить певну кількість мікросекунд.  Стандартне значення \- 1.
.SH ПАРАМЕТРИ
\fI--usage\fP
Показує коротку підказку по використанню.
.TP
\fI--help, -?\fP
Друкує підказку.
.TP
\fI-v, --version\fP
Виводить на екран інформацію про версію.
.SH ПОМИЛКИ
Можливі похибки на багатьох машинах до мікросекунди.  Розраховуйте на
точність тільки до  -4 або можливо -5.
.SH АВТОР
Donald Barnes <djb@redhat.com>
.br
Erik Troan <ewt@redhat.com>
.SH
ПЕРЕКЛАД
.br
Дмитро Ковальов, <kov@tokyo.emai.ne.jp>
